### ISSUE TITLE
Commands for CPU?

### ISSUE THREAD

**Issue by dadatawajue** [DmitryUlyanov/online-neural-doodle#2]
Hello, I'm trying to figure out how to get this running on CPU since I don't have nvidia..

I'm able to run `python generate.py --n_jobs 1 --n_colors 4 --style_image data/starry/style.png --style_mask data/starry/style_mask.png --out_hdf5 data/starry/gen_doodles.hdf5` successfully (have some DataConversionWarning but I guess it's no big deal), but I'm unable to run the 'learn a network' command since it complain about no luarocks module found for cunn,

I also tried to run with **-backend nn** and **-backend nn|cudnn** :
`CUDA_VISIBLE_DEVICES=0 th feedforward_neural_doodle.lua -model_name skip_noise_4 -masks_hdf5 data/starry/gen_doodles.hdf5 -batch_size 4 -num_mask_noise_times 0 -num_noise_channels 0 -learning_rate 1e-1 -backend nn -half false`
but it still complains about module 'cunn' not found

**Comment by DmitryUlyanov** [comment]
Hello, unfortunately, you need a powerful GPU to train the modes, preferably with 12 GB memory, sorry.

**Comment by dadatawajue** [comment]
Alright, thanks!

Are there any other solutions you'd recommend for less powerful computers without nvidia?

**Comment by DmitryUlyanov** [comment]
Unfortunately no, you can easily modify the code to run in CPU mode actually, but the training will take a week...

**Comment by dadatawajue** [comment]
Alright, thanks a lot!

**Comment by sunyiyou** [comment]
I just want to generate the image and could you give me more details about how to implement the CPU version?

**Comment by DmitryUlyanov** [comment]
Just go to http://likemo.net/ and try there.

**Comment by sunyiyou** [comment]
No no, I am working on a small application but not a demo. However, I did not have a handy GPU currently. I'd like to generate the images by pretrained models. I think that it will not spend too much time. How could I change the code so as to support the CPU?
